version: '0'
services:
  chatbot:
    image: chatbot:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
        - "9001:9000"
    restart: unless-stopped
    working_dir: /app
    environment:
        -  OPENAI_API_KEY=${OPENAI_API_KEY}
